Week3
Sammels/Sammels-Learn-programmig-in-python pull request #4
Opened 2021-09-13 12:39 UTC by Sammels

Я немного не понял всё ещё с `for`, а именно 3+ вложения. Буду дальше разбираться.

2021-09-14 09:49 UTC, statz requested changes

2021-09-14 09:49 UTC, statz commented on Week3_task/3_work_with_files_in_python.py
> +        new_file = wrt_file.write(read_file().replace('.', '!'))
зачем тут переменная?

2021-09-14 09:49 UTC, statz commented on Week3_task/Repeat_task/basic/for_challenges.py
> +    if is_male[names] is True:
Решение принимаю. В качестве задачи со звездочкой: как можно сделать в одну строчку?

2021-09-14 09:49 UTC, statz commented on Week3_task/Repeat_task/basic/for_challenges.py
> +    group_list += 1
попробуй enumerate

2021-09-14 09:49 UTC, statz commented on Week3_task/Repeat_task/basic/for_dict_challenges.py
> +names_count = {name:names.count(name) for name in names}
у нас список names не уникальный, значит для каждого name будет выполняться count несколько раз

2021-09-14 09:49 UTC, statz commented on Week3_task/Repeat_task/basic/for_dict_challenges.py
> +names_count = {name:names.count(name) for name in names}
ну и Counter.most_common есть, если готовое использовать)

2021-09-14 09:49 UTC, statz commented on Week3_task/Repeat_task/basic/for_dict_challenges.py
> +# Задание 5
попробуй сделать функцию в 4 задании и переиспользовать в 5

2021-09-14 09:49 UTC, statz commented on Week3_task/Repeat_task/basic/string_challenges.py
> +count_a = word_list.count('а')
а другие гласные?

2021-09-14 09:49 UTC, statz commented on Week3_task/Repeat_task/basic/string_challenges.py
> +firs_word = sent_list[0][0]
ну для произвольной строки же нужно сделать

2021-09-14 09:49 UTC, statz commented on Week3_task/Repeat_task/basic/string_challenges.py
> +firs_word = sent_list[0]
то же самое

2021-09-16 11:20 UTC, Sammels commented on Week3_task/Repeat_task/basic/for_challenges.py
> +    if is_male[names] is True:
for name in names: print(f'{name}: {len(name)}')
Такую конструкцию исплользовать ? )

2021-09-16 11:25 UTC, Sammels commented on Week3_task/3_work_with_files_in_python.py
> +        new_file = wrt_file.write(read_file().replace('.', '!'))
Убрал, за ненадобностью.

2021-09-16 13:21 UTC, statz commented on Week3_task/Repeat_task/basic/for_challenges.py
> +    if is_male[names] is True:
ну тутвопрос, как избавиться от  4 строчек if-else. Например, посмотреть в сторону тернарного оператора

2021-09-23 08:41 UTC, statz commented on Web_start/weather.py
> +		if 'current_condition' in weather['data']:
можно в один if объединить

2021-09-23 08:41 UTC, statz commented on Week3_task/OOP_train/5_1_OOP_legacy.py
> +        return f'<Phone name: {self.name}, price: {self.price}, stock: {self.stock}>'
А как сделать так, чтобы __repr__  был только в классе родителе?

2021-09-23 08:41 UTC, statz commented on Week3_task/OOP_train/5_1_OOP_legacy.py
> +        return f'<Phone name: {self.name}, price: {self.price}, stock: {self.stock}>'
это на подумать

2021-09-23 08:41 UTC, statz commented on Week3_task/Repeat_task/basic/for_challenges.py
> +for name in names: print(f'{name}: {len(name)}')
а зачем в одну строчку?

2021-09-23 14:45 UTC, Sammels commented on Week3_task/OOP_train/5_1_OOP_legacy.py
> +        return f'<Phone name: {self.name}, price: {self.price}, stock: {self.stock}>'
Прописать в родительском классе репр для каждого метода ?

2021-09-23 14:46 UTC, Sammels commented on Web_start/weather.py
> +		if 'current_condition' in weather['data']:
if 'data' in weather and if 'current_condition' in weather['data']: ?

2021-09-24 09:26 UTC, statz commented on Week3_task/OOP_train/5_1_OOP_legacy.py
> +        return f'<Phone name: {self.name}, price: {self.price}, stock: {self.stock}>'
ну скорее можно сделать что-то типа self.name=='Product' и его подставлять в f-string, а в классах наследниках менять его) Тогда repr нужно будет сделать только один раз

2021-10-05 15:04 UTC, merged